### ISSUE TITLE
Can't enable the plugin on an older miencraft version.

### ISSUE THREAD

**Issue by sakurawald** [Brokkonaut/LWCEntityLocking#6]
```
[18:58:15 INFO]: [LWC] Enabling LWC v5.0.16
[18:58:15 ERROR]: Error occurred while enabling LWC v5.0.16 (Is it up to date?)
java.lang.NoSuchFieldError: MANGROVE_WALL_SIGN
        at com.griefcraft.modules.limits.LimitsV2.<clinit>(LimitsV2.java:53) ~[?:?]
        at com.griefcraft.lwc.LWC.registerCoreModules(LWC.java:1538) ~[?:?]
        at com.griefcraft.lwc.LWC.load(LWC.java:1485) ~[?:?]
        at com.griefcraft.lwc.LWCPlugin.onEnable(LWCPlugin.java:217) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[forge:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) ~[forge:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479) ~[forge:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501) ~[forge:7e29f765-296df566-9fb885e8]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413) ~[forge:7e29f765-296df566-9fb885e8]
        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:213) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771) ~[?:?]
        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:58:15 INFO]: [LWC] Disabling LWC v5.0.16
```

yes, i am on a older minecraft version, so i just want to know which is the correct LWC version for me.

```
> version
[17:44:09 INFO]: This server is running Mohist version 1.16.5-1061 (MC: 1.16.5) (Implementing API version 1.16.5-R0.1-SNAPSHOT, Forge version 36.2.39)
>
```

**Comment by Brokkonaut** [comment]
Build 80 should work on 1.16.5: https://www.iani.de/jenkins/job/LWC/80/

**Comment by sakurawald** [comment]
I have tried many versions, but they got the same problem.
```
[00:49:31 INFO]: [Residence] Enabling Residence v5.0.1.7
[00:49:31 INFO]: [Residence] Loaded (2) groups
[00:49:31 INFO]: [Residence] Found Vault, but Vault reported no usable permissions system...
[00:49:31 INFO]: [Residence] Permissions plugin NOT FOUND!
[00:49:31 WARN]: java.lang.NoClassDefFoundError: com/griefcraft/scripting/Module
[00:49:31 WARN]:        at java.base/java.lang.ClassLoader.defineClass1(Native Method)
[00:49:31 WARN]:        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
[00:49:31 WARN]:        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
[00:49:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.remappedFindClass(PluginClassLoader.java:253)
[00:49:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:176)
[00:49:31 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
[00:49:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:116)
[00:49:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:111)
[00:49:31 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[00:49:31 WARN]:        at com.bekvon.bukkit.residence.Residence.onEnable(Residence.java:526)
[00:49:31 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
[00:49:31 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335)
[00:49:31 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:479)
[00:49:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:501)
[00:49:31 WARN]:        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:413)
[00:49:31 WARN]:        at net.minecraft.server.MinecraftServer.func_240787_a_(MinecraftServer.java:429)
[00:49:31 WARN]:        at net.minecraft.server.MinecraftServer.func_240800_l__(MinecraftServer.java:349)
[00:49:31 WARN]:        at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:221)
[00:49:31 WARN]:        at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:771)
[00:49:31 WARN]:        at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:269)
[00:49:31 WARN]:        at java.base/java.lang.Thread.run(Thread.java:833)
[00:49:31 WARN]: Caused by: java.lang.ClassNotFoundException: com.griefcraft.scripting.Module
[00:49:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:152)
[00:49:31 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:111)
[00:49:31 WARN]:        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
[00:49:31 WARN]:        ... 21 more
[00:49:31 INFO]: [Residence] Scanning for economy systems...
```

**Comment by Brokkonaut** [comment]
This is something different. Looks like the Residence plugin (com.bekvon.bukkit.residence.Residence) is not compatible to this lwc version

**Comment by Brokkonaut** [comment]
I'm not sure what is going wrong there, because the interface com.griefcraft.scripting.Module (that is called missing in the exception) definitely exists. Are there any other related errors?

**Comment by sakurawald** [comment]
> I'm not sure what is going wrong there, because the interface com.griefcraft.scripting.Module (that is called missing in the exception) definitely exists. Are there any other related errors?

no, this exception only occurs after i installed the LWC plugins.

**Comment by sakurawald** [comment]
> > I'm not sure what is going wrong there, because the interface com.griefcraft.scripting.Module (that is called missing in the exception) definitely exists. Are there any other related errors?
> 
> no, this exception only occurs after i installed the LWC plugins.
it seems a plugin hook problem. if i use the latest version LWC, i got
```
[18:58:15 ERROR]: Error occurred while enabling LWC v5.0.16 (Is it up to date?)
java.lang.NoSuchFieldError: MANGROVE_WALL_SIGN
```
since my Residence is the latest version, i don't know if it's ok to use the latest LWC plugin. (but the biggest problem is that my server core is 1.16.5, so it's no compatible with the latest version LWC, maybe LWC should avoid to get some unexisist fields and just skip these items)

**Comment by Brokkonaut** [comment]
Yes the latest build is definitely not compatible with Minecraft 1.16.5 - Build 80 should work, at least the warning in https://github.com/Brokkonaut/LWCEntityLocking/issues/6#issuecomment-1193355658 is just a warning for the hook but lwc should still work if that is the only error.
